/* tslint:disable */
/* eslint-disable */
/**
 * Customer Risk Assessment
 * Customer Risk Assessment
 *
 * OpenAPI spec version: ekyc-08
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/cp4admin-customer-risk-assessment-customer-risk-assessment-api';

