/* tslint:disable */
/* eslint-disable */
/**
 * Customer Risk Assessment
 * Customer Risk Assessment
 *
 * OpenAPI spec version: ekyc-08
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CustomerRiskAssessmentRisk0020AssessmentOutput
 */
export interface CustomerRiskAssessmentRisk0020AssessmentOutput {
    /**
     * 
     * @type {string}
     * @memberof CustomerRiskAssessmentRisk0020AssessmentOutput
     */
    customerRiskAssessmentRating?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerRiskAssessmentRisk0020AssessmentOutput
     */
    customerRiskAssessmentScore?: number;
}
