/* tslint:disable */
/* eslint-disable */
/**
 * Customer Risk Assessment
 * Customer Risk Assessment
 *
 * OpenAPI spec version: ekyc-08
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The description of the decision execution failure.
 * @export
 * @interface Customer0020Risk0020AssessmentIncident
 */
export interface Customer0020Risk0020AssessmentIncident {
    /**
     * A unique identifier for the incident.
     * @type {string}
     * @memberof Customer0020Risk0020AssessmentIncident
     */
    incidentId?: string;
    /**
     * The category of the incident, for instance \"Decision not found\".
     * @type {string}
     * @memberof Customer0020Risk0020AssessmentIncident
     */
    incidentCategory?: string;
    /**
     * An associated stack trace, if the decision runtime is configured to provide it. By default, the stack trace is null.
     * @type {string}
     * @memberof Customer0020Risk0020AssessmentIncident
     */
    stackTrace?: string;
}
