/* tslint:disable */
/* eslint-disable */
/**
 * Customer Risk Assessment
 * Customer Risk Assessment
 *
 * OpenAPI spec version: ekyc-08
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CustomerRiskAssessmentRisk0020AssessmentInput
 */
export interface CustomerRiskAssessmentRisk0020AssessmentInput {
    /**
     * 
     * @type {string}
     * @memberof CustomerRiskAssessmentRisk0020AssessmentInput
     */
    nonPersonalEntityType?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerRiskAssessmentRisk0020AssessmentInput
     */
    nonPersonalGeographyType?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerRiskAssessmentRisk0020AssessmentInput
     */
    nonPersonalIndustryType?: string;
}
