/* tslint:disable */
/* eslint-disable */
/**
 * Customer Risk Assessment
 * Customer Risk Assessment
 *
 * OpenAPI spec version: ekyc-08
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Customer0020Risk0020AssessmentIncident } from '../models';
import { CustomerRiskAssessmentRisk0020AssessmentInput } from '../models';
import { CustomerRiskAssessmentRisk0020AssessmentOutput } from '../models';
/**
 * Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApi - axios parameter creator
 * @export
 */
export const Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Execute Customer-Risk-Assessment-Risk Assessment
         * @param {CustomerRiskAssessmentRisk0020AssessmentInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customerRiskAssessmentRiskAssessment: async (body?: CustomerRiskAssessmentRisk0020AssessmentInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Customer-Risk-Assessment-Risk%20Assessment/execute`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ZEN required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApi - functional programming interface
 * @export
 */
export const Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Execute Customer-Risk-Assessment-Risk Assessment
         * @param {CustomerRiskAssessmentRisk0020AssessmentInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async customerRiskAssessmentRiskAssessment(body?: CustomerRiskAssessmentRisk0020AssessmentInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CustomerRiskAssessmentRisk0020AssessmentOutput>>> {
            const localVarAxiosArgs = await Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApiAxiosParamCreator(configuration).customerRiskAssessmentRiskAssessment(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApi - factory interface
 * @export
 */
export const Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Execute Customer-Risk-Assessment-Risk Assessment
         * @param {CustomerRiskAssessmentRisk0020AssessmentInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async customerRiskAssessmentRiskAssessment(body?: CustomerRiskAssessmentRisk0020AssessmentInput, options?: AxiosRequestConfig): Promise<AxiosResponse<CustomerRiskAssessmentRisk0020AssessmentOutput>> {
            return Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApiFp(configuration).customerRiskAssessmentRiskAssessment(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApi - object-oriented interface
 * @export
 * @class Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApi
 * @extends {BaseAPI}
 */
export class Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApi extends BaseAPI {
    /**
     * Execute Customer-Risk-Assessment-Risk Assessment
     * @param {CustomerRiskAssessmentRisk0020AssessmentInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApi
     */
    public async customerRiskAssessmentRiskAssessment(body?: CustomerRiskAssessmentRisk0020AssessmentInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<CustomerRiskAssessmentRisk0020AssessmentOutput>> {
        return Cp4adminCustomerRiskAssessmentCustomerRiskAssessmentApiFp(this.configuration).customerRiskAssessmentRiskAssessment(body, options).then((request) => request(this.axios, this.basePath));
    }
}
